#!/bin/bash

# Retrieve the script path
SCRIPT=$(readlink -f "$0")
SCRIPTPATH=$(dirname "$SCRIPT")

# Define the source and destination paths
clone_path="$SCRIPTPATH/symbols"
output_path="$SCRIPTPATH/symbols.txt"

# Clone the latest KiCAD footprints from repository if not already present
if [ ! -d "$clone_path" ]; then
    git clone --depth 1 https://gitlab.com/kicad/libraries/kicad-symbols.git "$clone_path"
else 
    cd "$clone_path"
    git pull
    cd "$SCRIPTPATH"
fi

# Empty the output file
> "$output_path"

# Put a header in the output file
echo "# This file contains all the KiCad symbols available in the official library" >> "$output_path"
echo "# Generated by symbols.sh" >> "$output_path"
echo "# on $(date)" >> "$output_path"

# Iterate over all kicad_sym files and extract the symbol names
for file in $(find "$clone_path" -type f -name "*.kicad_sym"); do
    # Extract the symbol name from the file
    # This line give us something like: '(symbol "74LS574"'
    symbols=$(grep -oP "\(symbol \"(.+)\"" $file)
    
    # Now we just need to extract the part from the quotes for each line
    # This line give us something like: 74LS574
    symbols=$(echo "$symbols" | sed "s|(symbol \"||" | sed "s|\"||")

    # Remove all symbols that end with something like _1_2, as these are subunits
    symbols=$(echo "$symbols" | grep -Pv "_[0-9]+_[0-9]+$")

    # Now prepend the filename to the symbol name
    # This line give us something like: 74xx:74LS574
    symbols=$(echo "$symbols" | sed "s|^|$file:|" | sed "s|$clone_path/||" | sed "s|.kicad_sym||" | sed "s|/|:|" )

    # Sort symbols alphabetically
    symbols=$(echo "$symbols" | sort)

    if [ ! -z "$symbols" ]; then
        echo "$symbols" >> "$output_path"
    fi
done

echo "Found $(wc -l < "$output_path") symbols"